Added css class names "today" and "tomorrow" for calendar
MichMich/MagicMirror pull request #2939
Opened 2022-10-08 14:53 UTC by retroflex

Added class names "today" and "tomorrow" on the calendar module tr elements (i.e. calendar items).
This way you can for example color your events today and/or tomorrow to more easily see what's happening in the near future.

Implemented by adding an event.tomorrow variable (similar to event.today) that can be used for other things in the future. Also replaced a few hardcoded values (hours, seconds etc.) with constants to make the code more consistent.

2022-10-09 06:37 UTC, rejas commented
Nice idea, thwnks. would you feel confident writing a test for this feature?

2022-10-09 07:05 UTC, rejas commented
Nice idea, thwnks. would you feel confident writing a test for this feature?

2022-10-09 07:06 UTC, rejas requested changes

2022-10-09 09:38 UTC, retroflex commented on modules/default/calendar/calendar.js
> +		const oneSecond = 1000; // 1,000 milliseconds
Fixed

2022-10-09 09:44 UTC, retroflex commented
> Nice idea, thwnks. would you feel confident writing a test for this feature?

@rejas I haven't written tests for MagicMirror or node/js before, so not really. I had a quick check and it seems it uses test ics files: https://github.com/MichMich/MagicMirror/tree/master/tests/configs/data
Not sure how to build an ics file containing events for today and tomorrow, as that would depend on when the test is executed. Any ideas?

2022-10-09 10:10 UTC, rejas commented
The trick would be here to change (mock) the date of the system when running the test. Something similar could be either in compliments/weather/calendar tests...

2022-10-09 11:55 UTC, retroflex commented
@rejas after upgrading npm & node I got the tests to run with: npm run test:e2e
Is there any way to just run the calendar test?

2022-10-09 13:55 UTC, rejas commented
I think by adding the filename of the test behind the jest call in the nom script in package json

2022-10-09 15:42 UTC, retroflex commented
This worked fine: `npm run test:e2e -- calendar_spec.js`
Or to run unit tests too: `npm run test -- calendar_spec.js`

However when running it on my RPi3b I get this: 
```Error: Could not load script: "http://localhost:8080/modules/default/calendar/calendar.js```

And after that this: ```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
Aborted
```

So as much as I like tests, I'm not sure I'll get anywhere with this.

2022-10-11 18:50 UTC, rejas approved these changes

2022-10-11 19:04 UTC, rejas commented
Yes, adding tests here is not that easy. I opened a ticket for a general solution to this: https://github.com/MichMich/MagicMirror/issues/2942

And your PR will be merged now, thanks for the work!

2022-10-11 19:05 UTC, merged

2022-10-11 19:33 UTC, retroflex commented
Thanks s lot @rejas