Use template literals instead of string concatenation
MichMich/MagicMirror pull request #3066
Opened 2023-03-14 20:20 UTC by KristjanESPERANTO

We have used it inconsistently till now. Template literals are more modern and easier to maintain in my opinion.

Because that's a large amount of changes, here's a way to reproduce it: I added the rule `"prefer-template": "error"` to the `.eslintrc.json` and did an autofix. Since this caused a new problem in line 409 of `newsfeed.js`, I reversed it in that line and also removed the rule from the eslint config file.

The rule is described here: https://eslint.org/docs/latest/rules/prefer-template

Note: I've played around with some other linter rules as well, and some seem to point to some specific, non-cosmetic, issues. But before I dive even deeper and then introduce even bigger and hardly understandable changes at once, I thought I'd start with this simple cosmetic rule.

2023-03-14 20:30 UTC, khassel approved these changes

2023-03-19 12:22 UTC, rejas commented
Good PR. I would vote for adding the rule to the eslint config and add one "// disable" exception to the line in the newsfeed module. That way we stay "modern" and can fix the line maybe later :-)

2023-03-19 12:22 UTC, rejas requested changes
add rule to eslintrc and add exception to the one line in newsfeed module

2023-03-19 13:05 UTC, KristjanESPERANTO commented
I just did the following:
- fixed the problematic line
- added the rule (`"prefer-template": "error"`)
- removed a redundant rule (`"prettier/prettier": "error"`) - This change has nothing to do with the other changes, but is too minor for an extra PR.

2023-03-19 13:32 UTC, merged