AnimateCSS
MichMich/MagicMirror pull request #3113
Opened 2023-05-28 12:21 UTC by bugsounet

Hi,

This is my testing code for AnimateCSS for `show()`, `hide()`, `updateDom()`

Naturally, we have to do better !

I voluntarily modify `newsfeed` and `compliments` in order to test

2023-05-28 13:08 UTC, bugsounet commented
ok... I will solve localy :/

2023-05-28 21:37 UTC, bugsounet commented
So...

I purpose to you to make a test with `newsfeed` module
just change lines 304 and 308 with : `this.updateDom(this.config.animationSpeed, 3, 14);`

syntax: `updateDom(speed, animateOut, animateIn)`
animateOut, animateIn number value are available [there](https://github.com/bugsounet/MagicMirror/blob/develop/js/animateCSS.js) and it's the result of the animated names from the [Animate.style website](https://animate.style/)

2023-06-05 20:01 UTC, khassel commented
> Result: The news will come from the left, wait in the middle and come out the right

tested this with the same result

2023-06-06 16:30 UTC, bugsounet commented
@rejas says `Start with a very simple animation so we can discuss the actual implementation?`

I know, I have to do better implementation
It's just a testing code actually.

Should I do better? (Of course)
Are you really interested in this optional feature?

2023-06-06 18:26 UTC, rejas commented
> @rejas says `Start with a very simple animation so we can discuss the actual implementation?`
> 
> I know, I have to do better implementation It's just a testing code actually.
> 
> Should I do better? (Of course) Are you really interested in this optional feature?

Sorry for not being more active on your PR, I really like the feature but with a newborn I cant concentrate right now much on these PRs (contrary to small stuff like dependency updates that dont take much brain power)

Expect more feedback next week, then I might have more time to think about it.

2023-06-06 18:48 UTC, bugsounet commented
@rejas: congratulations to you ! This is happiness !

Take your time, a newborn is more important than this PR (I know the time and energy it takes!)

2023-06-10 09:00 UTC, bugsounet commented
I will try to do something cleaner because a test code is not made to be in production

2023-06-10 12:40 UTC, bugsounet commented
I realize that it's not that easy to do something cleaner

2023-06-10 20:53 UTC, rejas commented
> just change lines 304 and 308 with : `this.updateDom(this.config.animationSpeed, 3, 14);`

Would it be possible to have something more "verbose" when calling the updateDom? Something more like `this.updateDom(this.config.animationSpeed, Animate.Bounce, Animate.FadeOut);`
which would make it more readable for developers?

Also what do you think about having the module animation configurable (just like position):
```
		{
			module: "clock",
			position: "top_left",
                        animateIn: "bounce",
                        animateOut: "fade_out",
		},
```

?

As for the cleanliness of the code: I dont mind testing code in there, as long as the API to the modules is well-thought of. The actual implementation can be changed easily later, the API stays for a long time :-)

2023-06-11 12:29 UTC, bugsounet commented
Oh yes!!! very good idea.
I will try to do something about it

You prefer `Animate.Bounce` , `Animate.FadeOut`, `Animate.xxx`
I will create an object to manage this then

On the other hand, what bothers me, if we put all the animations in the same object that would mean that we can use the "animateOut" in the "animateIn" and vice versa
That's why I separated the animations

I think you would like that if the name of the requested animation does not exist, we fall back on the default MM² animation

Warning:
  * don't forget that animations add a class at the module position (it's add `animate__animated <animation name>` classes)
  * this necessarily breaks the test suite
  * You will have to review your test suite :/

2023-06-11 16:26 UTC, bugsounet commented
(sometime e2e scares me...)

2023-06-11 16:49 UTC, bugsounet commented
Right !

So i have added like you have says:

```
		{
			module: "compliments",
			position: "lower_third",
			animateIn: "bounceIn",
			animateOut: "bounceOut"
		},
```

`this.updateDom(this.config.animationSpeed, "bounceOut" , "bounceIn");` is available too

`this.hide(<speed>, { animate: <animateName> })`
and naturally the same with `show()`

Note: if a user have defined `animateIn` and/or `animateOut` in the module definition : MM² with use it in priority and will not apply `updateDom`, `hide`, `show` rules coded by the developer
I think this allows the end user to choose what he wants to have as animation with his own configuration

2023-06-11 19:21 UTC, bugsounet commented
Just because humm... I'm crazy !

I just add possibility to use animateIn on start of MM²

@rejas : what do you think about that ?

2023-09-02 10:43 UTC, bugsounet commented
@rejas : Veeck,
this must be good for me

If you want to see again ;)

2023-09-05 06:49 UTC, rejas requested changes

2023-09-05 06:49 UTC, rejas commented on js/animateCSS.js
> +const _AnimateCSSIn = [
that _ in front of the name is a Pattern we dont use anywhere else. what should it signal?

2023-09-05 06:49 UTC, rejas commented on js/animateCSS.js
> +const _AnimateCSSOut = [
same here, why the _ ?

2023-09-05 06:49 UTC, rejas commented on js/main.js
> +			var haveAnimateIn = null;
Please use let/const instead of var in your code

2023-09-05 06:49 UTC, rejas commented on js/main.js
> +		updateDom: function (module, speed, animateOut, animateIn) {
in a perfect world we would refactor the sighanture to 
(module, {options: {
 speed,
 animate: {
  out,
  in
}) and have a fallback to the old signature. what do you think?

2023-09-05 06:49 UTC, rejas commented on js/module.js
> +		// is it really useful? (not sure)
what should it be useful for?

2023-09-05 06:50 UTC, rejas commented
sorry for the long turnaroundtime, lots of stuff to do and the cold is already creeping in...

2023-09-06 18:46 UTC, bugsounet commented
no problem, I'm just doing my best for the next release :)

Note: when #3179 is fixed, can you retry test suite?
It's works in local but...

Thx Veeck

2023-09-06 23:01 UTC, KristjanESPERANTO commented
With #3181 the test shouldn't fail anymore.

I'm looking forward to this feature. Thanks @bugsounet :slightly_smiling_face:

2023-09-07 04:37 UTC, rejas commented
Merged develop myseld, lets see the test results  :-)

2023-09-07 05:12 UTC, bugsounet commented
Happy crazy test! 😁

2023-09-07 05:49 UTC, rejas requested changes

2023-09-07 05:49 UTC, rejas commented on js/main.js
> +				if (typeof updateOptions.options === "object" && updateOptions.options.speed !== undefined) {
is the first typeof check in this line necessary? its already done the line before...

2023-09-07 05:49 UTC, rejas commented on js/main.js
> +		updateDom: function (module, speed, animateOut, animateIn) {
thx for the refactor

2023-09-08 05:43 UTC, rejas commented
Ah, screw it, will merge it, we can cleanup further later if necessary (and I dont want to have @bugsounet waiting longer). This is too nice to not have, thx a lot for your work!

2023-09-08 05:43 UTC, merged

2023-09-08 07:50 UTC, bugsounet commented
I will start to write MagicMirror Doc

Note: It’s a shame there isn’t a develop branch on the doc
To see the result of the formatting once written (and correct if necessary)

2023-09-08 08:40 UTC, bugsounet commented
we will also have to see with @MichMich
it would be perfect if we had a "point of view" develop of this branch

something like "https://dev-docs.magicmirror.builders/" to see develop branch result
just for see if formating is correct before merging it

2023-09-08 09:38 UTC, MichMich commented
I've added a `develop` branch to the docs repo which is synced with https://develop.docs.magicmirror.builders. Let me know if there is anything else I can do.

2023-09-08 09:44 UTC, bugsounet commented
Thx @MichMich,
It's perfect for the moment !

2023-09-16 07:24 UTC, bugsounet commented
@rejas:

I see this bugs:

 * AnimateCSS merge hide() and show() animated css class when we do multiple call

--> result it will stay en hide state

I think event listener (is animateCSS file) is not a proper solution
I will correct soon as possible