Prevent too frequent request for sample ical
MichMich/MagicMirror pull request #3137
Opened 2023-06-28 11:55 UTC by eouia

Recently `CalendarLab` told me they have troubles due to Too many/frequent requests from MagicMirror Project. 
So they will change their URL scheme and service privately per user. 

This commit is changing the `5min` update cycle to `30min`.
But anyway, the example of config should be changed from 30th July.
(I'll post this thing detail in the community)

2023-06-28 12:20 UTC, rejas approved these changes

2023-06-28 12:36 UTC, rejas commented
Lets increase it even further to 1 day, I propose

2023-06-28 14:04 UTC, sdetweil commented
maybe once a week/month..  when was the last time a holiday was added?

with comments of course

is updateInterval by calendar url?

2023-06-28 14:14 UTC, eouia commented
At least, too short period (< 1min) fetching should be disallowed, I think.

2023-06-28 17:11 UTC, rejas commented
> maybe once a week/month.. when was the last time a holiday was added?

true. 

> is updateInterval by calendar url?

no, its for the whole module. adding a per calendar is feasible I think

> At least, too short period (< 1min) fetching should be disallowed, I think.

true. 

maybe I find the time tonight to extend your PR. Or do you want to tackle it @eouia ?

2023-06-28 20:35 UTC, rejas requested changes
please increase the interval even further

2023-06-29 00:14 UTC, eouia commented
> please increase the interval even further

I’m outside atm so cannot modify it. If anyone who ca this, do it instead of me.

2023-06-29 01:10 UTC, sdetweil commented
the default needs to be higher too...  force people to reset it

2023-06-29 06:23 UTC, brs-234 commented
I am a dev from Calendarlabs.com

Ideally, the fetch interval of the holiday calendar should be seven days. (Holiday calendar may get occasionally updated when the country has religious holidays). Most calendar applications default the refresh rate to a week (Ex: calendar app in any Apple device). At the same time, some calendar, like weather needs an hourly refresh

We created a separate URL to be included in config.js.sample file as default. However, users should always be encouraged to pick up their unique URL from the iCal calendar page. (so that they don't fall on the request pool assigned to the default URL)

https://ics.calendarlabs.com/76/mm3137/US_Holidays.ics

The URL has been allowed to accept up to 100,000 requests per day. We will adjust the volume as needed. (currently, there are around three thousand MM systems making requests for the ics URL.

2023-06-29 08:31 UTC, rejas commented
> I’m outside atm so cannot modify it. If anyone who can do this exists, plz do it instead of me.

If you grant edit access for the maintainers then I can work directly on this branch.

2023-06-29 11:14 UTC, eouia commented
> > I’m outside atm so cannot modify it. If anyone who can do this exists, plz do it instead of me.
> 
> @eouia If you grant edit access for the maintainers then I can work directly on this branch.

#3139 would be instead of mine. I don’t care.

2023-06-29 11:17 UTC, rejas commented
> #3139 would be instead of mine. I don’t care.

I'd liek to work on your brnach instead on my draft (so you can get credit too ;-) Plus we have the discussion ehre, so it makes sense to merge this one.

So please add the checkmark on the right that allows edit of maintainers etc

2023-06-29 13:01 UTC, eouia commented
Sorry I cannot find "Allow edits from maintainers." checkbox", (Don't know why) Maybe is it not allowed by setting?
Anyway, I don't care the credit itself. 
And CalendarLab will change the URL to privately, so our example URL should be changed from 30th Jul. So, this fetch itself is not so important, we need a new example URL alternative.

2023-06-29 13:05 UTC, rejas commented
> Sorry I cannot find "Allow edits from maintainers." checkbox", (Don't know why) Maybe is it not allowed by setting?

Isnt it on the right side for you? 
<img width="357" alt="grafik" src="https://github.com/MichMich/MagicMirror/assets/1313547/1e930e3b-4119-4c88-8bc2-bf568e288bac">

2023-06-29 16:39 UTC, brs-234 commented
> Sorry I cannot find "Allow edits from maintainers." checkbox", (Don't know why) Maybe is it not allowed by setting?
> Anyway, I don't care the credit itself.
> And CalendarLab will change the URL to a private one per registered user, so our example URL should be changed from 30th Jul. So, this fetch itself is not so important, we need a new example URL alternative.

Hi,
URL which we have provided in our last comment is an example url. This url is public and do not require any login.

you will always get updated content from this url.

I’m pasting the url here again for your reference 

https://ics.calendarlabs.com/76/mm3137/US_Holidays.ics

Thanks

2023-06-29 19:55 UTC, khassel commented
@rejas 

```bash
karsten13@karsten13 MINGW64 /z/foreign/MagicMirror (develop)
$ git fetch origin pull/3137/head:configIssue
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 6 (delta 3), reused 6 (delta 3), pack-reused 0
Unpacking objects: 100% (6/6), 1.30 KiB | 3.00 KiB/s, done.
From github.com:MichMich/MagicMirror
 * [new ref]           refs/pull/3137/head -> configIssue
```

see https://docs.github.com/de/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally#modifying-an-inactive-pull-request-locally

after the above `git fetch ...` you have the branch `configIssue` locally and can work on it. I did not test pushing.

2023-06-30 16:10 UTC, eouia commented
> > Sorry I cannot find "Allow edits from maintainers." checkbox", (Don't know why) Maybe is it not allowed by setting?
> 
> Isnt it on the right side of the page for you below the list of participants etc
> 
> <img alt="grafik" width="357" src="https://user-images.githubusercontent.com/1313547/249778800-1e930e3b-4119-4c88-8bc2-bf568e288bac.png">

I don't know why I can't find it. 
![스크린샷 2023-06-30 18 09 00](https://github.com/MichMich/MagicMirror/assets/1720610/e32a8dc2-2c6e-405a-a3a2-e97e89d973a2)

2023-06-30 16:39 UTC, rejas commented
Weird.... So, will probably have to merge my pr then...

2023-06-30 18:14 UTC, khassel commented
closing this now because https://github.com/MichMich/MagicMirror/pull/3139 was merged

2023-06-30 18:14 UTC, closed without merging