Update weathergov.js - new pull request against develop branch
MichMich/MagicMirror pull request #3195
Opened 2023-09-14 17:48 UTC by dgoth

Fixed issue with probability of precipitation not showing up on hourly or daily forecast

Hello and thank you for wanting to contribute to the MagicMirror² project

**Please make sure that you have followed these 4 rules before submitting your Pull Request:**

> 1. Base your pull requests against the `develop` branch.
>
> 2. Include these infos in the description:
>
> - Does the pull request solve a **related** issue?
> - If so, can you reference the issue like this `Fixes #<issue_number>`?
> - What does the pull request accomplish? Use a list if needed.
> - If it includes major visual changes please add screenshots.
>
> 3. Please run `npm run lint:prettier` before submitting so that
>    style issues are fixed.
>
> 4. Don't forget to add an entry about your changes to
>    the CHANGELOG.md file.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.

Thanks again and have a nice day!

2023-09-14 17:52 UTC, dgoth commented
Ok I tried creating a new pull request.

Sorry never actually contributed to github before

2023-09-14 18:04 UTC, rejas commented
No worries :-) 
Please add a CHANGELOG entry and run the prettier task over the files (and commit again) to get the checks green

2023-09-16 08:31 UTC, rejas requested changes
Please also add a CHANGELOG entry

2023-09-16 08:31 UTC, rejas commented on modules/default/weather/providers/weathergov.js
> +
Please run "npm run lint:prettier" and commit the changes.

2023-09-25 20:41 UTC, rejas approved these changes

2023-09-25 20:42 UTC, merged