Update yr provider to new api
MichMich/MagicMirror pull request #3197
Opened 2023-09-15 08:27 UTC by martingron

Some changes after yr api was deprecated and replaced with a new one.

Fixes #3189

2023-09-15 08:33 UTC, rejas requested changes

2023-09-15 08:33 UTC, rejas commented on package.json
> +		"start": ".\\node_modules\\.bin\\electron js\\electron.js",
Please revert these changes

2023-09-15 08:41 UTC, martingron commented on package.json
> +		"start": ".\\node_modules\\.bin\\electron js\\electron.js",
Done :)

2023-09-15 08:52 UTC, rejas reviewed
Thx, will check once I am back at a pc later today's

2023-09-15 12:44 UTC, rejas commented
One mall thing: run the linting task over the files and commit again.

2023-09-15 12:47 UTC, martingron commented
linting task?

2023-09-15 13:56 UTC, rejas commented
Npm run lint:prettier

2023-09-16 08:33 UTC, rejas requested changes
Please run `npm run lint:prettier` and commit the changes

2023-09-20 09:36 UTC, rejas approved these changes

2023-09-20 09:37 UTC, merged